xdp loader features
xdp-project/xdp-tools pull request #324
Opened 2023-05-24 10:17 UTC by LorenzoBianconi

Add features command to xdp-loader in order to dump XDP features supported by the NIC

2023-05-30 09:48 UTC, tohojo requested changes
A few comments. Also, CI is failing, PTAL...

2023-05-30 09:48 UTC, tohojo commented on xdp-loader/xdp-loader.c
> +	return -EOPNOTSUPP;
We should print a friendly error message here, not just return an error code. Same thing when the libbpf feature is there, but the kernel doesn't support querying features...

2023-05-30 09:48 UTC, tohojo commented on xdp-loader/xdp-loader.c
> +		      .metavar = "[ifname]",
This should be `<ifname>`, since the parameter is not optional...

2023-05-30 09:48 UTC, tohojo commented on xdp-loader/xdp-loader.c
> +		      .help = "Show XDP features for device [ifname]"),
...also here

2023-05-30 09:48 UTC, tohojo commented on xdp-loader/xdp-loader.8
> +The \fIfeatures\fP command displays the XDP features supported by the NIC.
We should also document what the possible features are, and what they mean.

2023-05-30 09:48 UTC, tohojo commented on xdp-loader/xdp-loader.c
> +	       CHECK_XDP_FEATURE(NETDEV_XDP_ACT_NDO_XMIT_SG));
What about future unknown features? At a minimum we should detect that there are unknown bits set and print a notice...

2023-06-01 20:57 UTC, tohojo requested changes
A few more nits, mostly UI things...

2023-06-01 20:57 UTC, tohojo commented on xdp-loader/xdp-loader.8
> +The netdev supports XDP_REDIRECT.
"The network device supports handling the XDP_REDIRECT return code. This means packets can be redirected *from* this device by XDP."

2023-06-01 20:57 UTC, tohojo commented on xdp-loader/xdp-loader.8
> +This feature informs if netdev implements ndo_xdp_xmit callback.
"The networking interfaces implements the ndo_xdp_xmit callback. This means packets can be redirected *to* this device by XDP."

2023-06-01 20:57 UTC, tohojo commented on xdp-loader/xdp-loader.8
> +This feature informs if netdev supports AF_XDP in zero copy mode.
"The networking device supports..." (let's be consistent with the phrasing)

2023-06-01 20:57 UTC, tohojo commented on xdp-loader/xdp-loader.8
> +This feature informs if netdev supports XDP hw offloading.
"The networking device supports..."

2023-06-07 10:52 UTC, tohojo requested changes
Code LGTM with a small nit in the test script. However, I totally missed that you were editing the man page file directly. That won't work: the man page is generated by the Makefile from `README.org`, so the changes have to go into that, and then the man page should be regenerated.

2023-06-07 12:26 UTC, LorenzoBianconi commented on xdp-loader/tests/test-xdp-loader.sh
> +    $XDP_LOADER features "$1" | grep "$2" | grep -q "$3"
@tohojo ack, I will fix it

2023-06-07 12:26 UTC, LorenzoBianconi commented
> Code LGTM with a small nit in the test script. However, I totally missed that you were editing the man page file directly. That won't work: the man page is generated by the Makefile from `README.org`, so the changes have to go into that, and then the man page should be regenerated.

@tohojo ack, I will fix it

2023-06-07 13:10 UTC, tohojo approved these changes

2023-06-07 14:31 UTC, tohojo requested changes

2023-06-07 21:49 UTC, tohojo approved these changes

2023-06-08 11:47 UTC, merged