Set BPF Skeleton name to base name of ebpf file
xdp-project/xdp-tools pull request #436
Opened 2024-09-09 15:14 UTC by jalalmostafa

The current build system sets the name of the generated skeleton directly to the file's name minus the `.skel.h` suffix.
Passing names of eBPF targets that contain a directory will result in wrong names e.g. `bpf/xdp_program.bpf.o` will have a skeleton file of the name `bpf/xdp_program.skel.h` and consequently the program name will be `bpf/xdp_program` instead of `xdp_program`. The commit pops out the directory part from the name.

2024-09-10 14:34 UTC, jalalmostafa commented
Not a bug but more of a feature. I use the xdp-tools build system as a scaffold for my libxdp-based programs. If I or someone else wants to have the eBPF programs in a special directory then he needs this.

2024-09-11 10:39 UTC, tohojo commented
Hmm, okay, well I guess this doesn't hurt to include. Do note that using the repository like this is not something that's explicitly supported, so I won't promise not to make changes that you'll have to adapt to :)

2024-09-11 10:40 UTC, tohojo requested changes
Could you please update the commit message to include the rationale (including the fact that this does not affect anything currently in the repo)?

2024-09-16 09:07 UTC, jalalmostafa commented
I just fixed the commit message. I added removing *.ll files in nested directories in the `clean` target too.

2024-09-19 10:21 UTC, tohojo requested changes
The DCO bot is complaining that the commit author and S-o-b tag; please fix that (you can reset the author with `git commit --amend --author=`, or just change the S-o-b tag.

2024-09-19 10:21 UTC, tohojo commented on lib/common.mk
> +	$(Q)rm -f $(USER_TARGETS) $(XDP_OBJ) $(TEST_TARGETS) $(USER_OBJ) $(TEST_OBJ) $(USER_GEN) $(BPF_SKEL_H) *.ll **/*.ll
Please drop this change. It is way too broad to include in the repository, and relies on the shell expanding `**` correctly, which is not a given.

2024-09-19 14:37 UTC, tohojo commented
Better, but now the commit message disappeared again :(

2024-09-19 15:25 UTC, jalalmostafa commented
Oops. Sorry. 
I just added it.

2024-09-19 16:21 UTC, tohojo approved these changes
Alright, that's better, thanks! :)

2024-09-19 16:24 UTC, merged