xdp-bench: Enable the xdp_frags flag for dummy programs
xdp-project/xdp-tools pull request #451
Opened 2024-11-05 15:15 UTC by nimrod-oren

Before this commit, the redirect dummy programs would fail to load on interfaces with non-linear MTU.

2024-11-06 09:43 UTC, tohojo commented
Any particular reason why this is marked as draft? :)

2024-11-14 16:11 UTC, nimrod-oren commented
ready for review :)

2024-11-14 17:03 UTC, tohojo requested changes
Ah, seems I don't get an email notification when the state changes.

Could you please add the description (from the first comment on the PR) into the commit message as well? PR comments are not saved as part of the git history...

2024-11-17 07:52 UTC, nimrod-oren commented
Done.

2024-11-18 12:19 UTC, merged