xdp: add xdp_multiprog__defunct to detect severed multiprog
xdp-project/xdp-tools pull request #98
Opened 2021-03-08 02:59 UTC by kkdwivedi

This allows the user to determine if a multiprog is already detached,
due to the removal of the net_device it was attached to. This in turn
allows a program to clean up its multiprog dispatcher in the bpffs XDP
directory.

Meanwhile, make the ID helpers take their argument by const.

Signed-off-by: Kumar Kartikeya Dwivedi <memxor@gmail.com>

2021-03-08 22:00 UTC, tohojo commented
Hmm, how is the caller supposed to obtain a struct xdp_multiprog reference to the program if it's not attached to an interface? And also, what is the caller supposed to do with the information returned by xdp_multiprog__defunct()?

Since the objective is garbage collecting the pinned files, I think maybe we just need a `libxdp_clean_references(ifindex)` type interface? Where it's also possible to pass in 0 as an ifindex to walk all the pinned programs in the pin directory and clean them. This could then be tied into an xdp-loader action...

2021-03-09 01:31 UTC, kkdwivedi commented
> Since the objective is garbage collecting the pinned files, I think maybe we just need a `libxdp_clean_references(ifindex)` type interface? Where it's also possible to pass in 0 as an ifindex to walk all the pinned programs in the pin directory and clean them. This could then be tied into an xdp-loader action...

Sounds good, I'll push with this change and the `xdp-loader collect` part.

2021-03-09 14:37 UTC, kkdwivedi commented
This should be ready for review now.

2021-03-09 21:06 UTC, tohojo requested changes

2021-03-09 21:06 UTC, tohojo commented on headers/xdp/libxdp.h
> +int xdp_clean_references(int ifindex);
Let's prefix this with libxdp_ instead of xdp_ and put it at the top with libxdp_get_error() and libxdp_strerror()

2021-03-09 21:06 UTC, tohojo commented on lib/libxdp/libxdp.c
> +static __u32 xdp_multiprog__main_id(const struct xdp_multiprog *mp)
Please put these in a separate commit

2021-03-09 21:06 UTC, tohojo commented on lib/libxdp/libxdp.c
> +static void xdp_get_ifindex_prog_id(int ifindex, __u32 *prog_id)
Why not just return the prog_id instead of having a point in a void function?

2021-03-09 21:06 UTC, tohojo commented on lib/libxdp/libxdp.c
> +	DIR *d = NULL;
We generally try to use the 'reverse x-mas tree' variable ordering from the kernel netdev tradition

2021-03-09 21:06 UTC, tohojo commented on lib/libxdp/libxdp.c
> +	DIR *d = NULL;
Same as above - reverse x-mas tree, please. Also, just put the two __u32s on the same line

2021-03-09 21:06 UTC, tohojo commented on lib/libxdp/libxdp.c
> +	if (!ifindex) {
Instead of this...

2021-03-09 21:06 UTC, tohojo commented on lib/libxdp/libxdp.c
> +
...just add a check if the ifindex is set and matches here (and continue if it doesn't)...

2021-03-09 21:06 UTC, tohojo commented on lib/libxdp/libxdp.c
> +	} else {
... and you can avoid the duplication here.

2021-03-09 21:06 UTC, tohojo commented on lib/libxdp/libxdp.c
> +	closedir(d);
order these as the reverse of what you did at the top?

2021-03-09 21:06 UTC, tohojo commented on xdp-loader/xdp-loader.c
> +		"       collect     - clean up dead links in XDP bpffs directory\n"
Let's just name the action 'clean' as well - and don't forget to update the man page (README.org) as well

2021-03-09 22:14 UTC, kkdwivedi commented
Pushed, PTAL.

2021-03-17 16:29 UTC, tohojo requested changes
Functionality wise this is fine now, just a few more nits on the output and documentation...

2021-03-17 16:29 UTC, tohojo commented on lib/libxdp/libxdp.c
> +			err = remove_pin_dir(dent->d_name);
A debug line here saying what's going on would be good (including whether the prog ID changed or if nothing is attached now)...

2021-03-17 16:29 UTC, tohojo commented on xdp-loader/README.org
> +* The CLEAN command
For consistency with the other commands, please add an explicit "the syntax for the =clean= command is" bit that includes the [ifindex] parameter.

2021-03-17 16:29 UTC, tohojo commented on xdp-loader/xdp-loader.c
> +	printf("Cleaning up detached XDP program links...\n");
This should include whether we're cleaning all interfaces or just the one. Also, ending with an ellipsis implies there will be more output coming, so just end with a period.

2021-03-18 05:00 UTC, kkdwivedi commented
Pushed again, PTAL.

2021-03-18 10:08 UTC, merged

2021-03-18 10:08 UTC, tohojo commented
Fixed up the log message and merged - thanks! :)